export const MIN_LENGTH_FOR_USERNAME = 3;
export const MAX_LENGTH_FOR_SEARCH = 4;
export const MIN_LENGTH_FOR_SEARCH = 250;
export const NOTIFICATION_DESCRIPTION_ELLIPSIS_COUNT = 4;
export const NOTIFICATION_DESCRIPTION_MAX_CHAR_COUNT = 120;